import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const write = process.argv.includes('--write');
const inventoryPath = path.join(root, 'scripts/workspace/inventory.json');
const versionPath = path.join(root, 'version.json');
const version = JSON.parse(fs.readFileSync(versionPath, 'utf8')).version;
if (typeof version !== 'string' || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) throw new Error(`Invalid version in version.json: ${version}`);
const inventory = JSON.parse(fs.readFileSync(inventoryPath, 'utf8'));
const packages = inventory.packages ?? [];
const publicPackages = packages.filter(p => p.private !== true);
const names = new Set(packages.map(p => p.name));
const errors = [];
for (const p of publicPackages) {
    const manifestPath = path.join(root, p.path, 'package.json');
    if (!fs.existsSync(manifestPath)) { errors.push(`${p.name}: missing ${p.path}/package.json`); continue; }
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    if (manifest.name !== p.name) errors.push(`${p.path}: inventory name ${p.name} does not match manifest ${manifest.name}`);
    if (write && manifest.version !== version) { manifest.version = version; fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n'); } else if (manifest.version !== version) errors.push(`${p.name}: version ${manifest.version} should be ${version}`);
    for (const field of ['dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies']) {
        for (const [name, range] of Object.entries(manifest[field] ?? {})) {
            if (names.has(name) && range !== 'workspace:*') errors.push(`${p.name}: ${field}.${name} should use workspace:* (found ${range})`);
        }
    }
}
for (const p of publicPackages) if (!fs.existsSync(path.join(root, p.path, 'package.json'))) errors.push(`inventory entry has no manifest: ${p.name}`);
if (errors.length) throw new Error(errors.join('\n'));
if (write) {
    const plugin = packages.find(p => p.name === '@molstar/plugin');
    const target = plugin ? path.join(root, plugin.path, 'src/version.ts') : path.join(root, 'src/mol-plugin/version.ts');
    if (fs.existsSync(target)) {
        const previous = fs.readFileSync(target, 'utf8');
        const previousVersion = previous.match(/PLUGIN_VERSION\s*=\s*['"]([^'"]+)['"]/u)?.[1];
        const previousTimestamp = previous.match(/PLUGIN_VERSION_DATE\s*=\s*new Date\((\d+)\)/u)?.[1];
        const timestampValue = process.env.MOLSTAR_BUILD_TIMESTAMP
            ?? (previousVersion === version && previousTimestamp ? previousTimestamp : Date.now());
        const timestamp = Number(timestampValue);
        if (!Number.isSafeInteger(timestamp)) throw new Error(`Invalid MOLSTAR_BUILD_TIMESTAMP: ${timestampValue}`);
        const generated = `/** Generated by scripts/workspace/version.mjs. */\nexport const PLUGIN_VERSION = '${version}';\nexport const PLUGIN_VERSION_DATE = new Date(${Number(timestamp)});\n`;
        if (previous !== generated) fs.writeFileSync(target, generated);
    }
} else console.log(`Workspace package versions match ${version}.`);
