/* tslint:disable */
/** Generated in 2018-10-31T12:19:29-07:00 */

// ====================================================
// START: Typescript template
// ====================================================

// ====================================================
// Scalars
// ====================================================

/** Built-in scalar representing an instant in time */
export type Date = any;

// ====================================================
// Enums
// ====================================================

export enum ChemCompPdbxIdealCoordinatesMissingFlag {
  N = "N",
  Y = "Y"
}

export enum ChemCompPdbxModelCoordinatesMissingFlag {
  N = "N",
  Y = "Y"
}

export enum ChemCompPdbxProcessingSite {
  EBI = "EBI",
  PDBE = "PDBE",
  PDBJ = "PDBJ",
  RCSB = "RCSB"
}

export enum ChemCompPdbxReleaseStatus {
  DEL = "DEL",
  HOLD = "HOLD",
  HPUB = "HPUB",
  OBS = "OBS",
  REF_ONLY = "REF_ONLY",
  REL = "REL"
}

export enum ChemCompType {
  DNA_LINKING = "DNA_LINKING",
  DNA_OH_3_PRIME_TERMINUS = "DNA_OH_3_PRIME_TERMINUS",
  DNA_OH_5_PRIME_TERMINUS = "DNA_OH_5_PRIME_TERMINUS",
  D_BETA_PEPTIDE_C_GAMMA_LINKING = "D_BETA_PEPTIDE_C_GAMMA_LINKING",
  D_GAMMA_PEPTIDE_C_DELTA_LINKING = "D_GAMMA_PEPTIDE_C_DELTA_LINKING",
  D_PEPTIDE_COOH_CARBOXY_TERMINUS = "D_PEPTIDE_COOH_CARBOXY_TERMINUS",
  D_PEPTIDE_LINKING = "D_PEPTIDE_LINKING",
  D_PEPTIDE_NH_3_AMINO_TERMINUS = "D_PEPTIDE_NH_3_AMINO_TERMINUS",
  D_SACCHARIDE = "D_SACCHARIDE",
  D_SACCHARIDE_1_4_AND_1_4_LINKING = "D_SACCHARIDE_1_4_AND_1_4_LINKING",
  D_SACCHARIDE_1_4_AND_1_6_LINKING = "D_SACCHARIDE_1_4_AND_1_6_LINKING",
  L_BETA_PEPTIDE_C_GAMMA_LINKING = "L_BETA_PEPTIDE_C_GAMMA_LINKING",
  L_DNA_LINKING = "L_DNA_LINKING",
  L_GAMMA_PEPTIDE_C_DELTA_LINKING = "L_GAMMA_PEPTIDE_C_DELTA_LINKING",
  L_PEPTIDE_COOH_CARBOXY_TERMINUS = "L_PEPTIDE_COOH_CARBOXY_TERMINUS",
  L_PEPTIDE_LINKING = "L_PEPTIDE_LINKING",
  L_PEPTIDE_NH_3_AMINO_TERMINUS = "L_PEPTIDE_NH_3_AMINO_TERMINUS",
  L_RNA_LINKING = "L_RNA_LINKING",
  L_SACCHARIDE = "L_SACCHARIDE",
  L_SACCHARIDE_1_4_AND_1_4_LINKING = "L_SACCHARIDE_1_4_AND_1_4_LINKING",
  L_SACCHARIDE_1_4_AND_1_6_LINKING = "L_SACCHARIDE_1_4_AND_1_6_LINKING",
  NON_POLYMER = "NON_POLYMER",
  OTHER = "OTHER",
  PEPTIDE_LIKE = "PEPTIDE_LIKE",
  PEPTIDE_LINKING = "PEPTIDE_LINKING",
  RNA_LINKING = "RNA_LINKING",
  RNA_OH_3_PRIME_TERMINUS = "RNA_OH_3_PRIME_TERMINUS",
  RNA_OH_5_PRIME_TERMINUS = "RNA_OH_5_PRIME_TERMINUS",
  SACCHARIDE = "SACCHARIDE"
}

export enum ChemCompAtomPdbxAromaticFlag {
  N = "N",
  Y = "Y"
}

export enum ChemCompAtomPdbxLeavingAtomFlag {
  N = "N",
  Y = "Y"
}

export enum ChemCompAtomPdbxPolymerType {
  NON_POLYMER = "NON_POLYMER",
  POLYMER = "POLYMER"
}

export enum ChemCompAtomPdbxStereoConfig {
  N = "N",
  R = "R",
  S = "S"
}

export enum ChemCompBondPdbxAromaticFlag {
  N = "N",
  Y = "Y"
}

export enum ChemCompBondPdbxStereoConfig {
  E = "E",
  N = "N",
  Z = "Z"
}

export enum ChemCompBondValueOrder {
  AROM = "AROM",
  DELO = "DELO",
  DOUB = "DOUB",
  PI = "PI",
  POLY = "POLY",
  QUAD = "QUAD",
  SING = "SING",
  TRIP = "TRIP"
}

export enum PdbxChemCompAuditActionType {
  CREATE_COMPONENT = "CREATE_COMPONENT",
  INITIAL_RELEASE = "INITIAL_RELEASE",
  MODIFY_AROMATIC_FLAG = "MODIFY_AROMATIC_FLAG",
  MODIFY_ATOM_ID = "MODIFY_ATOM_ID",
  MODIFY_CHARGE = "MODIFY_CHARGE",
  MODIFY_COMPONENT_ATOM_ID = "MODIFY_COMPONENT_ATOM_ID",
  MODIFY_COMPONENT_COMP_ID = "MODIFY_COMPONENT_COMP_ID",
  MODIFY_COORDINATES = "MODIFY_COORDINATES",
  MODIFY_DESCRIPTOR = "MODIFY_DESCRIPTOR",
  MODIFY_FORMAL_CHARGE = "MODIFY_FORMAL_CHARGE",
  MODIFY_FORMULA = "MODIFY_FORMULA",
  MODIFY_IDENTIFIER = "MODIFY_IDENTIFIER",
  MODIFY_INTERNAL_TYPE = "MODIFY_INTERNAL_TYPE",
  MODIFY_LEAVING_ATOM_FLAG = "MODIFY_LEAVING_ATOM_FLAG",
  MODIFY_LINKING_TYPE = "MODIFY_LINKING_TYPE",
  MODIFY_MODEL_COORDINATES_CODE = "MODIFY_MODEL_COORDINATES_CODE",
  MODIFY_NAME = "MODIFY_NAME",
  MODIFY_ONE_LETTER_CODE = "MODIFY_ONE_LETTER_CODE",
  MODIFY_PARENT_RESIDUE = "MODIFY_PARENT_RESIDUE",
  MODIFY_PROCESSING_SITE = "MODIFY_PROCESSING_SITE",
  MODIFY_SUBCOMPONENT_LIST = "MODIFY_SUBCOMPONENT_LIST",
  MODIFY_SYNONYMS = "MODIFY_SYNONYMS",
  MODIFY_VALUE_ORDER = "MODIFY_VALUE_ORDER",
  OBSOLETE_COMPONENT = "OBSOLETE_COMPONENT",
  OTHER_MODIFICATION = "OTHER_MODIFICATION"
}

export enum PdbxChemCompDescriptorType {
  IN_CH_I = "IN_CH_I",
  IN_CH_I_CHARGE = "IN_CH_I_CHARGE",
  IN_CH_I_FIXEDH = "IN_CH_I_FIXEDH",
  IN_CH_I_ISOTOPE = "IN_CH_I_ISOTOPE",
  IN_CH_I_KEY = "IN_CH_I_KEY",
  IN_CH_I_MAIN = "IN_CH_I_MAIN",
  IN_CH_I_MAIN_CONNECT = "IN_CH_I_MAIN_CONNECT",
  IN_CH_I_MAIN_FORMULA = "IN_CH_I_MAIN_FORMULA",
  IN_CH_I_MAIN_HATOM = "IN_CH_I_MAIN_HATOM",
  IN_CH_I_RECONNECT = "IN_CH_I_RECONNECT",
  IN_CH_I_STEREO = "IN_CH_I_STEREO",
  SMILES = "SMILES",
  SMILES_CANNONICAL = "SMILES_CANNONICAL",
  SMILES_CANONICAL = "SMILES_CANONICAL"
}

export enum PdbxChemCompIdentifierType {
  CAS_REGISTRY_NUMBER = "CAS_REGISTRY_NUMBER",
  COMMON_NAME = "COMMON_NAME",
  CONDENSED_IUPAC_CARB_NAME = "CONDENSED_IUPAC_CARB_NAME",
  IUPAC_CARB_NAME = "IUPAC_CARB_NAME",
  MDL_IDENTIFIER = "MDL_IDENTIFIER",
  PUBCHEM_IDENTIFIER = "PUBCHEM_IDENTIFIER",
  SYNONYM = "SYNONYM",
  SYSTEMATIC_NAME = "SYSTEMATIC_NAME"
}

export enum PdbxStructAssemblyRcsbCandidateAssembly {
  N = "N",
  Y = "Y"
}

export enum PdbxStructAssemblyRcsbDetails {
  AUTHOR_AND_SOFTWARE_DEFINED_ASSEMBLY = "AUTHOR_AND_SOFTWARE_DEFINED_ASSEMBLY",
  AUTHOR_DEFINED_ASSEMBLY = "AUTHOR_DEFINED_ASSEMBLY",
  SOFTWARE_DEFINED_ASSEMBLY = "SOFTWARE_DEFINED_ASSEMBLY"
}

export enum PdbxStructAssemblyAuthEvidenceExperimentalSupport {
  ASSAY_FOR_OLIGOMERIZATION = "ASSAY_FOR_OLIGOMERIZATION",
  CROSS_LINKING = "CROSS_LINKING",
  EQUILIBRIUM_CENTRIFUGATION = "EQUILIBRIUM_CENTRIFUGATION",
  FLUORESCENCE_RESONANCE_ENERGY_TRANSFER = "FLUORESCENCE_RESONANCE_ENERGY_TRANSFER",
  GEL_FILTRATION = "GEL_FILTRATION",
  HOMOLOGY = "HOMOLOGY",
  IMMUNOPRECIPITATION = "IMMUNOPRECIPITATION",
  ISOTHERMAL_TITRATION_CALORIMETRY = "ISOTHERMAL_TITRATION_CALORIMETRY",
  LIGHT_SCATTERING = "LIGHT_SCATTERING",
  MASS_SPECTROMETRY = "MASS_SPECTROMETRY",
  MICROSCOPY = "MICROSCOPY",
  NATIVE_GEL_ELECTROPHORESIS = "NATIVE_GEL_ELECTROPHORESIS",
  NONE = "NONE",
  SAXS = "SAXS",
  SCANNING_TRANSMISSION_ELECTRON_MICROSCOPY = "SCANNING_TRANSMISSION_ELECTRON_MICROSCOPY",
  SURFACE_PLASMON_RESONANCE = "SURFACE_PLASMON_RESONANCE"
}

export enum PdbxStructAssemblyPropType {
  ABSA_A_2 = "ABSA_A_2",
  MORE = "MORE",
  SSA_A_2 = "SSA_A_2"
}

export enum PdbxStructOperListType {
  BUILD_2_D_CRYSTAL_ASYMMETRIC_UNIT = "BUILD_2_D_CRYSTAL_ASYMMETRIC_UNIT",
  BUILD_3_D_CRYSTAL_ASYMMETRIC_UNIT = "BUILD_3_D_CRYSTAL_ASYMMETRIC_UNIT",
  BUILD_HELICAL_ASYMMETRIC_UNIT = "BUILD_HELICAL_ASYMMETRIC_UNIT",
  BUILD_POINT_ASYMMETRIC_UNIT = "BUILD_POINT_ASYMMETRIC_UNIT",
  CRYSTAL_SYMMETRY_OPERATION = "CRYSTAL_SYMMETRY_OPERATION",
  HELICAL_SYMMETRY_OPERATION = "HELICAL_SYMMETRY_OPERATION",
  IDENTITY_OPERATION = "IDENTITY_OPERATION",
  POINT_SYMMETRY_OPERATION = "POINT_SYMMETRY_OPERATION",
  TRANSFORM_TO_2_D_CRYSTAL_FRAME = "TRANSFORM_TO_2_D_CRYSTAL_FRAME",
  TRANSFORM_TO_3_D_CRYSTAL_FRAME = "TRANSFORM_TO_3_D_CRYSTAL_FRAME",
  TRANSFORM_TO_CRYSTAL_FRAME = "TRANSFORM_TO_CRYSTAL_FRAME",
  TRANSFORM_TO_HELICAL_FRAME = "TRANSFORM_TO_HELICAL_FRAME",
  TRANSFORM_TO_POINT_FRAME = "TRANSFORM_TO_POINT_FRAME",
  _2_D_CRYSTAL_SYMMETRY_OPERATION = "_2_D_CRYSTAL_SYMMETRY_OPERATION",
  _3_D_CRYSTAL_SYMMETRY_OPERATION = "_3_D_CRYSTAL_SYMMETRY_OPERATION"
}

export enum RcsbStructSymmetryKind {
  GLOBAL = "GLOBAL",
  LOCAL = "LOCAL",
  PSEUDO = "PSEUDO"
}

export enum RcsbStructSymmetryType {
  ASYMMETRIC = "ASYMMETRIC",
  CYCLIC = "CYCLIC",
  DIHEDRAL = "DIHEDRAL",
  HELICAL = "HELICAL",
  ICOSAHEDRAL = "ICOSAHEDRAL",
  OCTAHEDRAL = "OCTAHEDRAL",
  TETRAHEDRAL = "TETRAHEDRAL"
}

export enum CitationCoordinateLinkage {
  N = "N",
  NO = "NO",
  Y = "Y",
  YES = "YES"
}

export enum CitationUnpublishedFlag {
  N = "N",
  Y = "Y"
}

export enum DiffrnRadiationPdbxMonochromaticOrLaueMl {
  L = "L",
  M = "M"
}

export enum DiffrnRadiationPdbxScatteringType {
  ELECTRON = "ELECTRON",
  NEUTRON = "NEUTRON",
  X_RAY = "X_RAY"
}

export enum Em2dCrystalEntitySpaceGroupNameHm {
  C_1_2 = "C_1_2",
  C_2_2_2 = "C_2_2_2",
  P_1 = "P_1",
  P_1_2 = "P_1_2",
  P_1_21 = "P_1_21",
  P_2 = "P_2",
  P_2_21_21 = "P_2_21_21",
  P_2_2_2 = "P_2_2_2",
  P_2_2_21 = "P_2_2_21",
  P_3 = "P_3",
  P_3_1_2 = "P_3_1_2",
  P_3_2_1 = "P_3_2_1",
  P_4 = "P_4",
  P_4_21_2 = "P_4_21_2",
  P_4_2_2 = "P_4_2_2",
  P_6 = "P_6",
  P_6_2_2 = "P_6_2_2"
}

export enum Em3dFittingRefProtocol {
  AB_INITIO_MODEL = "AB_INITIO_MODEL",
  BACKBONE_TRACE = "BACKBONE_TRACE",
  FLEXIBLE_FIT = "FLEXIBLE_FIT",
  OTHER = "OTHER",
  RIGID_BODY_FIT = "RIGID_BODY_FIT"
}

export enum Em3dFittingRefSpace {
  REAL = "REAL",
  RECIPROCAL = "RECIPROCAL"
}

export enum Em3dReconstructionRefinementType {
  HALF_MAPS_REFINED_AGAINST_SAME_DATA = "HALF_MAPS_REFINED_AGAINST_SAME_DATA",
  HALF_MAPS_REFINED_INDEPENDENTLY = "HALF_MAPS_REFINED_INDEPENDENTLY",
  HALF_MAPS_REFINED_INDEPENDENTLY_WITH_FREQUENCY_RANGE_OMITTED = "HALF_MAPS_REFINED_INDEPENDENTLY_WITH_FREQUENCY_RANGE_OMITTED",
  HALF_MAPS_REFINED_WITH_FREQUENCY_RANGE_OMITTED = "HALF_MAPS_REFINED_WITH_FREQUENCY_RANGE_OMITTED",
  OTHER = "OTHER"
}

export enum Em3dReconstructionSymmetryType {
  HELICAL = "HELICAL",
  POINT = "POINT",
  _2_D_CRYSTAL = "_2_D_CRYSTAL",
  _3_D_CRYSTAL = "_3_D_CRYSTAL"
}

export enum EmEntityAssemblySource {
  MULTIPLE_SOURCES = "MULTIPLE_SOURCES",
  NATURAL = "NATURAL",
  RECOMBINANT = "RECOMBINANT"
}

export enum EmExperimentAggregationState {
  CELL = "CELL",
  FILAMENT = "FILAMENT",
  HELICAL_ARRAY = "HELICAL_ARRAY",
  PARTICLE = "PARTICLE",
  TISSUE = "TISSUE",
  _2_D_ARRAY = "_2_D_ARRAY",
  _3_D_ARRAY = "_3_D_ARRAY"
}

export enum EmExperimentReconstructionMethod {
  CRYSTALLOGRAPHY = "CRYSTALLOGRAPHY",
  HELICAL = "HELICAL",
  SINGLE_PARTICLE = "SINGLE_PARTICLE",
  SUBTOMOGRAM_AVERAGING = "SUBTOMOGRAM_AVERAGING",
  TOMOGRAPHY = "TOMOGRAPHY"
}

export enum EmImageRecordingDetectorMode {
  COUNTING = "COUNTING",
  INTEGRATING = "INTEGRATING",
  OTHER = "OTHER",
  SUPER_RESOLUTION = "SUPER_RESOLUTION"
}

export enum EmImagingAlignmentProcedure {
  BASIC = "BASIC",
  COMA_FREE = "COMA_FREE",
  NONE = "NONE",
  OTHER = "OTHER",
  ZEMLIN_TABLEAU = "ZEMLIN_TABLEAU"
}

export enum EmImagingCryogen {
  HELIUM = "HELIUM",
  NITROGEN = "NITROGEN"
}

export enum EmImagingIlluminationMode {
  FLOOD_BEAM = "FLOOD_BEAM",
  OTHER = "OTHER",
  SPOT_SCAN = "SPOT_SCAN"
}

export enum EmImagingMicroscopeModel {
  FEI_MORGAGNI = "FEI_MORGAGNI",
  FEI_PHILIPS_CM_10 = "FEI_PHILIPS_CM_10",
  FEI_PHILIPS_CM_12 = "FEI_PHILIPS_CM_12",
  FEI_PHILIPS_CM_120_T = "FEI_PHILIPS_CM_120_T",
  FEI_PHILIPS_CM_200_FEG = "FEI_PHILIPS_CM_200_FEG",
  FEI_PHILIPS_CM_200_FEG_SOPHIE = "FEI_PHILIPS_CM_200_FEG_SOPHIE",
  FEI_PHILIPS_CM_200_FEG_ST = "FEI_PHILIPS_CM_200_FEG_ST",
  FEI_PHILIPS_CM_200_FEG_UT = "FEI_PHILIPS_CM_200_FEG_UT",
  FEI_PHILIPS_CM_200_T = "FEI_PHILIPS_CM_200_T",
  FEI_PHILIPS_CM_300_FEG_HE = "FEI_PHILIPS_CM_300_FEG_HE",
  FEI_PHILIPS_CM_300_FEG_ST = "FEI_PHILIPS_CM_300_FEG_ST",
  FEI_PHILIPS_CM_300_FEG_T = "FEI_PHILIPS_CM_300_FEG_T",
  FEI_PHILIPS_EM_400 = "FEI_PHILIPS_EM_400",
  FEI_PHILIPS_EM_420 = "FEI_PHILIPS_EM_420",
  FEI_POLARA_300 = "FEI_POLARA_300",
  FEI_TALOS_ARCTICA = "FEI_TALOS_ARCTICA",
  FEI_TECNAI_10 = "FEI_TECNAI_10",
  FEI_TECNAI_12 = "FEI_TECNAI_12",
  FEI_TECNAI_20 = "FEI_TECNAI_20",
  FEI_TECNAI_ARCTICA = "FEI_TECNAI_ARCTICA",
  FEI_TECNAI_F_20 = "FEI_TECNAI_F_20",
  FEI_TECNAI_F_30 = "FEI_TECNAI_F_30",
  FEI_TECNAI_SPHERA = "FEI_TECNAI_SPHERA",
  FEI_TECNAI_SPIRIT = "FEI_TECNAI_SPIRIT",
  FEI_TITAN = "FEI_TITAN",
  FEI_TITAN_KRIOS = "FEI_TITAN_KRIOS",
  HITACHI_EF_2000 = "HITACHI_EF_2000",
  HITACHI_EF_3000 = "HITACHI_EF_3000",
  HITACHI_HF_2000 = "HITACHI_HF_2000",
  HITACHI_HF_3000 = "HITACHI_HF_3000",
  HITACHI_H_7600 = "HITACHI_H_7600",
  HITACHI_H_9500_SD = "HITACHI_H_9500_SD",
  JEOL_100_B = "JEOL_100_B",
  JEOL_100_CX = "JEOL_100_CX",
  JEOL_1010 = "JEOL_1010",
  JEOL_1200 = "JEOL_1200",
  JEOL_1200_EX = "JEOL_1200_EX",
  JEOL_1200_EXII = "JEOL_1200_EXII",
  JEOL_1230 = "JEOL_1230",
  JEOL_1400 = "JEOL_1400",
  JEOL_2000_EX = "JEOL_2000_EX",
  JEOL_2000_EXII = "JEOL_2000_EXII",
  JEOL_2010 = "JEOL_2010",
  JEOL_2010_F = "JEOL_2010_F",
  JEOL_2010_HC = "JEOL_2010_HC",
  JEOL_2010_HT = "JEOL_2010_HT",
  JEOL_2010_UHR = "JEOL_2010_UHR",
  JEOL_2011 = "JEOL_2011",
  JEOL_2100 = "JEOL_2100",
  JEOL_2100_F = "JEOL_2100_F",
  JEOL_2200_FS = "JEOL_2200_FS",
  JEOL_2200_FSC = "JEOL_2200_FSC",
  JEOL_3000_SFF = "JEOL_3000_SFF",
  JEOL_3100_FEF = "JEOL_3100_FEF",
  JEOL_3100_FFC = "JEOL_3100_FFC",
  JEOL_3200_FS = "JEOL_3200_FS",
  JEOL_3200_FSC = "JEOL_3200_FSC",
  JEOL_4000 = "JEOL_4000",
  JEOL_4000_EX = "JEOL_4000_EX",
  JEOL_CRYO_ARM_200 = "JEOL_CRYO_ARM_200",
  JEOL_CRYO_ARM_300 = "JEOL_CRYO_ARM_300",
  JEOL_KYOTO_3000_SFF = "JEOL_KYOTO_3000_SFF",
  SIEMENS_SULEIKA = "SIEMENS_SULEIKA",
  ZEISS_LEO_912 = "ZEISS_LEO_912",
  ZEISS_LIBRA_120_PLUS = "ZEISS_LIBRA_120_PLUS"
}

export enum EmImagingMode {
  BRIGHT_FIELD = "BRIGHT_FIELD",
  DARK_FIELD = "DARK_FIELD",
  DIFFRACTION = "DIFFRACTION",
  OTHER = "OTHER"
}

export enum EmImagingSpecimenHolderModel {
  FEI_TITAN_KRIOS_AUTOGRID_HOLDER = "FEI_TITAN_KRIOS_AUTOGRID_HOLDER",
  FISCHIONE_INSTRUMENTS_DUAL_AXIS_TOMOGRAPHY_HOLDER = "FISCHIONE_INSTRUMENTS_DUAL_AXIS_TOMOGRAPHY_HOLDER",
  GATAN_626_SINGLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER = "GATAN_626_SINGLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER",
  GATAN_910_MULTI_SPECIMEN_SINGLE_TILT_CRYO_TRANSFER_HOLDER = "GATAN_910_MULTI_SPECIMEN_SINGLE_TILT_CRYO_TRANSFER_HOLDER",
  GATAN_914_HIGH_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_TOMOGRAPHY_HOLDER = "GATAN_914_HIGH_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_TOMOGRAPHY_HOLDER",
  GATAN_915_DOUBLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER = "GATAN_915_DOUBLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER",
  GATAN_CHDT_3504_DOUBLE_TILT_HIGH_RESOLUTION_NITROGEN_COOLING_HOLDER = "GATAN_CHDT_3504_DOUBLE_TILT_HIGH_RESOLUTION_NITROGEN_COOLING_HOLDER",
  GATAN_CT_3500_SINGLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER = "GATAN_CT_3500_SINGLE_TILT_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER",
  GATAN_CT_3500_TR_SINGLE_TILT_ROTATION_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER = "GATAN_CT_3500_TR_SINGLE_TILT_ROTATION_LIQUID_NITROGEN_CRYO_TRANSFER_HOLDER",
  GATAN_HCHDT_3010_DOUBLE_TILT_HIGH_RESOLUTION_HELIUM_COOLING_HOLDER = "GATAN_HCHDT_3010_DOUBLE_TILT_HIGH_RESOLUTION_HELIUM_COOLING_HOLDER",
  GATAN_HCHST_3008_SINGLE_TILT_HIGH_RESOLUTION_HELIUM_COOLING_HOLDER = "GATAN_HCHST_3008_SINGLE_TILT_HIGH_RESOLUTION_HELIUM_COOLING_HOLDER",
  GATAN_HC_3500_SINGLE_TILT_HEATING_NITROGEN_COOLING_HOLDER = "GATAN_HC_3500_SINGLE_TILT_HEATING_NITROGEN_COOLING_HOLDER",
  GATAN_HELIUM = "GATAN_HELIUM",
  GATAN_LIQUID_NITROGEN = "GATAN_LIQUID_NITROGEN",
  GATAN_UHRST_3500_SINGLE_TILT_ULTRA_HIGH_RESOLUTION_NITROGEN_COOLING_HOLDER = "GATAN_UHRST_3500_SINGLE_TILT_ULTRA_HIGH_RESOLUTION_NITROGEN_COOLING_HOLDER",
  GATAN_ULTDT_ULTRA_LOW_TEMPERATURE_DOUBLE_TILT_HELIUM_COOLING_HOLDER = "GATAN_ULTDT_ULTRA_LOW_TEMPERATURE_DOUBLE_TILT_HELIUM_COOLING_HOLDER",
  GATAN_ULTST_ULTRA_LOW_TEMPERATURE_SINGLE_TILT_HELIUM_COOLING_HOLDER = "GATAN_ULTST_ULTRA_LOW_TEMPERATURE_SINGLE_TILT_HELIUM_COOLING_HOLDER",
  HOME_BUILD = "HOME_BUILD",
  JEOL = "JEOL",
  JEOL_3200_FSC_CRYOHOLDER = "JEOL_3200_FSC_CRYOHOLDER",
  JEOL_CRYOSPECPORTER = "JEOL_CRYOSPECPORTER",
  OTHER = "OTHER",
  PHILIPS_ROTATION_HOLDER = "PHILIPS_ROTATION_HOLDER",
  SIDE_ENTRY_EUCENTRIC = "SIDE_ENTRY_EUCENTRIC"
}

export enum EmSoftwareCategory {
  CLASSIFICATION = "CLASSIFICATION",
  CRYSTALLOGRAPHY_MERGING = "CRYSTALLOGRAPHY_MERGING",
  CTF_CORRECTION = "CTF_CORRECTION",
  DIFFRACTION_INDEXING = "DIFFRACTION_INDEXING",
  FINAL_EULER_ASSIGNMENT = "FINAL_EULER_ASSIGNMENT",
  IMAGE_ACQUISITION = "IMAGE_ACQUISITION",
  INITIAL_EULER_ASSIGNMENT = "INITIAL_EULER_ASSIGNMENT",
  LATTICE_DISTORTION_CORRECTION = "LATTICE_DISTORTION_CORRECTION",
  LAYERLINE_INDEXING = "LAYERLINE_INDEXING",
  MASKING = "MASKING",
  MODEL_FITTING = "MODEL_FITTING",
  MODEL_REFINEMENT = "MODEL_REFINEMENT",
  MOLECULAR_REPLACEMENT = "MOLECULAR_REPLACEMENT",
  OTHER = "OTHER",
  PARTICLE_SELECTION = "PARTICLE_SELECTION",
  RECONSTRUCTION = "RECONSTRUCTION",
  SERIES_ALIGNMENT = "SERIES_ALIGNMENT",
  SYMMETRY_DETERMINATION = "SYMMETRY_DETERMINATION",
  VOLUME_SELECTION = "VOLUME_SELECTION"
}

export enum EmSpecimenEmbeddingApplied {
  NO = "NO",
  YES = "YES"
}

export enum EmSpecimenShadowingApplied {
  NO = "NO",
  YES = "YES"
}

export enum EmSpecimenStainingApplied {
  NO = "NO",
  YES = "YES"
}

export enum EmSpecimenVitrificationApplied {
  NO = "NO",
  YES = "YES"
}

export enum EmStainingType {
  NEGATIVE = "NEGATIVE",
  NONE = "NONE",
  POSITIVE = "POSITIVE"
}

export enum EmVitrificationCryogenName {
  ETHANE = "ETHANE",
  ETHANE_PROPANE = "ETHANE_PROPANE",
  FREON_12 = "FREON_12",
  FREON_22 = "FREON_22",
  HELIUM = "HELIUM",
  METHANE = "METHANE",
  NITROGEN = "NITROGEN",
  OTHER = "OTHER",
  PROPANE = "PROPANE"
}

export enum EmVitrificationInstrument {
  EMS_002_RAPID_IMMERSION_FREEZER = "EMS_002_RAPID_IMMERSION_FREEZER",
  FEI_VITROBOT_MARK_I = "FEI_VITROBOT_MARK_I",
  FEI_VITROBOT_MARK_II = "FEI_VITROBOT_MARK_II",
  FEI_VITROBOT_MARK_III = "FEI_VITROBOT_MARK_III",
  FEI_VITROBOT_MARK_IV = "FEI_VITROBOT_MARK_IV",
  GATAN_CRYOPLUNGE_3 = "GATAN_CRYOPLUNGE_3",
  HOMEMADE_PLUNGER = "HOMEMADE_PLUNGER",
  LEICA_EM_CPC = "LEICA_EM_CPC",
  LEICA_EM_GP = "LEICA_EM_GP",
  LEICA_KF_80 = "LEICA_KF_80",
  LEICA_PLUNGER = "LEICA_PLUNGER",
  REICHERT_JUNG_PLUNGER = "REICHERT_JUNG_PLUNGER",
  SPOTITON = "SPOTITON",
  ZEISS_PLUNGE_FREEZER_CRYOBOX = "ZEISS_PLUNGE_FREEZER_CRYOBOX"
}

export enum EntityRcsbMultipleSourceFlag {
  N = "N",
  Y = "Y"
}

export enum EntitySrcMethod {
  MAN = "MAN",
  NAT = "NAT",
  SYN = "SYN"
}

export enum EntityType {
  BRANCHED = "BRANCHED",
  MACROLIDE = "MACROLIDE",
  NON_POLYMER = "NON_POLYMER",
  POLYMER = "POLYMER",
  WATER = "WATER"
}

export enum EntityPolyNstdLinkage {
  N = "N",
  NO = "NO",
  Y = "Y",
  YES = "YES"
}

export enum EntityPolyNstdMonomer {
  N = "N",
  NO = "NO",
  Y = "Y",
  YES = "YES"
}

export enum EntityPolyType {
  CYCLIC_PSEUDO_PEPTIDE = "CYCLIC_PSEUDO_PEPTIDE",
  OTHER = "OTHER",
  PEPTIDE_NUCLEIC_ACID = "PEPTIDE_NUCLEIC_ACID",
  POLYDEOXYRIBONUCLEOTIDE = "POLYDEOXYRIBONUCLEOTIDE",
  POLYDEOXYRIBONUCLEOTIDE_POLYRIBONUCLEOTIDE_HYBRID = "POLYDEOXYRIBONUCLEOTIDE_POLYRIBONUCLEOTIDE_HYBRID",
  POLYPEPTIDE_D = "POLYPEPTIDE_D",
  POLYPEPTIDE_L = "POLYPEPTIDE_L",
  POLYRIBONUCLEOTIDE = "POLYRIBONUCLEOTIDE",
  POLYSACCHARIDE_D = "POLYSACCHARIDE_D",
  POLYSACCHARIDE_L = "POLYSACCHARIDE_L"
}

export enum EntitySrcGenPdbxAltSourceFlag {
  MODEL = "MODEL",
  SAMPLE = "SAMPLE"
}

export enum EntitySrcGenPdbxSeqType {
  BIOLOGICAL_SEQUENCE = "BIOLOGICAL_SEQUENCE",
  C_TERMINAL_TAG = "C_TERMINAL_TAG",
  LINKER = "LINKER",
  N_TERMINAL_TAG = "N_TERMINAL_TAG"
}

export enum EntitySrcNatPdbxAltSourceFlag {
  MODEL = "MODEL",
  SAMPLE = "SAMPLE"
}

export enum PdbxEntitySrcSynPdbxAltSourceFlag {
  MODEL = "MODEL",
  SAMPLE = "SAMPLE"
}

export enum RcsbEntityHostOrganismProvenanceCode {
  PDB_PRIMARY_DATA = "PDB_PRIMARY_DATA"
}

export enum RcsbEntitySourceOrganismProvenanceCode {
  PDB_PRIMARY_DATA = "PDB_PRIMARY_DATA"
}

export enum RcsbEntitySourceOrganismSourceType {
  GENETICALLY_ENGINEERED = "GENETICALLY_ENGINEERED",
  NATURAL = "NATURAL",
  SYNTHETIC = "SYNTHETIC"
}

export enum RcsbMembraneProvenanceSource {
  HOMOLOGY = "HOMOLOGY",
  MPSTRUCT = "MPSTRUCT"
}

export enum StructAsymPdbxBlankPdbChainidFlag {
  N = "N",
  Y = "Y"
}

export enum FeatureType {
  ACTIVE_SITE = "ACTIVE_SITE",
  BINDING_SITE = "BINDING_SITE",
  CALCIUM_BINDING_REGION = "CALCIUM_BINDING_REGION",
  CHAIN = "CHAIN",
  COILED_COIL_REGION = "COILED_COIL_REGION",
  COMPOSITIONALLY_BIASED_REGION = "COMPOSITIONALLY_BIASED_REGION",
  CROSS_LINK = "CROSS_LINK",
  DISULFIDE_BOND = "DISULFIDE_BOND",
  DNA_BINDING_REGION = "DNA_BINDING_REGION",
  DOMAIN = "DOMAIN",
  GLYCOSYLATION_SITE = "GLYCOSYLATION_SITE",
  HELIX = "HELIX",
  INITIATOR_METHIONINE = "INITIATOR_METHIONINE",
  INTRAMEMBRANE_REGION = "INTRAMEMBRANE_REGION",
  LIPID_MOIETY_BINDING_REGION = "LIPID_MOIETY_BINDING_REGION",
  METAL_ION_BINDING_SITE = "METAL_ION_BINDING_SITE",
  MODIFIED_RESIDUE = "MODIFIED_RESIDUE",
  MUTAGENESIS_SITE = "MUTAGENESIS_SITE",
  NON_CONSECUTIVE_RESIDUES = "NON_CONSECUTIVE_RESIDUES",
  NON_STANDARD_AMINO_ACID = "NON_STANDARD_AMINO_ACID",
  NON_TERMINAL_RESIDUE = "NON_TERMINAL_RESIDUE",
  NUCLEOTIDE_PHOSPHATE_BINDING_REGION = "NUCLEOTIDE_PHOSPHATE_BINDING_REGION",
  PEPTIDE = "PEPTIDE",
  PROPEPTIDE = "PROPEPTIDE",
  REGION_OF_INTEREST = "REGION_OF_INTEREST",
  REPEAT = "REPEAT",
  SEQUENCE_CONFLICT = "SEQUENCE_CONFLICT",
  SEQUENCE_VARIANT = "SEQUENCE_VARIANT",
  SHORT_SEQUENCE_MOTIF = "SHORT_SEQUENCE_MOTIF",
  SIGNAL_PEPTIDE = "SIGNAL_PEPTIDE",
  SITE = "SITE",
  SPLICE_VARIANT = "SPLICE_VARIANT",
  STRAND = "STRAND",
  TOPOLOGICAL_DOMAIN = "TOPOLOGICAL_DOMAIN",
  TRANSIT_PEPTIDE = "TRANSIT_PEPTIDE",
  TRANSMEMBRANE_REGION = "TRANSMEMBRANE_REGION",
  TURN = "TURN",
  UNSURE_RESIDUE = "UNSURE_RESIDUE",
  ZINC_FINGER_REGION = "ZINC_FINGER_REGION"
}

export enum GeneNameType {
  ORDERED_LOCUS = "ORDERED_LOCUS",
  ORF = "ORF",
  PRIMARY = "PRIMARY",
  SYNONYM = "SYNONYM"
}

export enum OrganismNameType {
  ABBREVIATION = "ABBREVIATION",
  COMMON = "COMMON",
  FULL = "FULL",
  SCIENTIFIC = "SCIENTIFIC",
  SYNONYM = "SYNONYM"
}

export enum OrganismHostNameType {
  ABBREVIATION = "ABBREVIATION",
  COMMON = "COMMON",
  FULL = "FULL",
  SCIENTIFIC = "SCIENTIFIC",
  SYNONYM = "SYNONYM"
}

export enum ExptlMethod {
  ELECTRON_CRYSTALLOGRAPHY = "ELECTRON_CRYSTALLOGRAPHY",
  ELECTRON_MICROSCOPY = "ELECTRON_MICROSCOPY",
  EPR = "EPR",
  FIBER_DIFFRACTION = "FIBER_DIFFRACTION",
  FLUORESCENCE_TRANSFER = "FLUORESCENCE_TRANSFER",
  INFRARED_SPECTROSCOPY = "INFRARED_SPECTROSCOPY",
  NEUTRON_DIFFRACTION = "NEUTRON_DIFFRACTION",
  POWDER_DIFFRACTION = "POWDER_DIFFRACTION",
  SOLID_STATE_NMR = "SOLID_STATE_NMR",
  SOLUTION_NMR = "SOLUTION_NMR",
  SOLUTION_SCATTERING = "SOLUTION_SCATTERING",
  THEORETICAL_MODEL = "THEORETICAL_MODEL",
  X_RAY_DIFFRACTION = "X_RAY_DIFFRACTION"
}

export enum PdbxSgProjectFullNameOfCenter {
  ACCELERATED_TECHNOLOGIES_CENTER_FOR_GENE_TO_3_D_STRUCTURE = "ACCELERATED_TECHNOLOGIES_CENTER_FOR_GENE_TO_3_D_STRUCTURE",
  ASSEMBLY_DYNAMICS_AND_EVOLUTION_OF_CELL_CELL_AND_CELL_MATRIX_ADHESIONS = "ASSEMBLY_DYNAMICS_AND_EVOLUTION_OF_CELL_CELL_AND_CELL_MATRIX_ADHESIONS",
  ATOMS_TO_ANIMALS_THE_IMMUNE_FUNCTION_NETWORK = "ATOMS_TO_ANIMALS_THE_IMMUNE_FUNCTION_NETWORK",
  BACTERIAL_TARGETS_AT_IGS_CNRS_FRANCE = "BACTERIAL_TARGETS_AT_IGS_CNRS_FRANCE",
  BERKELEY_STRUCTURAL_GENOMICS_CENTER = "BERKELEY_STRUCTURAL_GENOMICS_CENTER",
  CENTER_FOR_EUKARYOTIC_STRUCTURAL_GENOMICS = "CENTER_FOR_EUKARYOTIC_STRUCTURAL_GENOMICS",
  CENTER_FOR_HIGH_THROUGHPUT_STRUCTURAL_BIOLOGY = "CENTER_FOR_HIGH_THROUGHPUT_STRUCTURAL_BIOLOGY",
  CENTER_FOR_MEMBRANE_PROTEINS_OF_INFECTIOUS_DISEASES = "CENTER_FOR_MEMBRANE_PROTEINS_OF_INFECTIOUS_DISEASES",
  CENTER_FOR_STRUCTURAL_GENOMICS_OF_INFECTIOUS_DISEASES = "CENTER_FOR_STRUCTURAL_GENOMICS_OF_INFECTIOUS_DISEASES",
  CENTER_FOR_STRUCTURES_OF_MEMBRANE_PROTEINS = "CENTER_FOR_STRUCTURES_OF_MEMBRANE_PROTEINS",
  CENTER_FOR_THE_X_RAY_STRUCTURE_DETERMINATION_OF_HUMAN_TRANSPORTERS = "CENTER_FOR_THE_X_RAY_STRUCTURE_DETERMINATION_OF_HUMAN_TRANSPORTERS",
  CHAPERONE_ENABLED_STUDIES_OF_EPIGENETIC_REGULATION_ENZYMES = "CHAPERONE_ENABLED_STUDIES_OF_EPIGENETIC_REGULATION_ENZYMES",
  ENZYME_DISCOVERY_FOR_NATURAL_PRODUCT_BIOSYNTHESIS = "ENZYME_DISCOVERY_FOR_NATURAL_PRODUCT_BIOSYNTHESIS",
  GPCR_NETWORK = "GPCR_NETWORK",
  INTEGRATED_CENTER_FOR_STRUCTURE_AND_FUNCTION_INNOVATION = "INTEGRATED_CENTER_FOR_STRUCTURE_AND_FUNCTION_INNOVATION",
  ISRAEL_STRUCTURAL_PROTEOMICS_CENTER = "ISRAEL_STRUCTURAL_PROTEOMICS_CENTER",
  JOINT_CENTER_FOR_STRUCTURAL_GENOMICS = "JOINT_CENTER_FOR_STRUCTURAL_GENOMICS",
  MARSEILLES_STRUCTURAL_GENOMICS_PROGRAM_AFMB = "MARSEILLES_STRUCTURAL_GENOMICS_PROGRAM_AFMB",
  MEDICAL_STRUCTURAL_GENOMICS_OF_PATHOGENIC_PROTOZOA = "MEDICAL_STRUCTURAL_GENOMICS_OF_PATHOGENIC_PROTOZOA",
  MEMBRANE_PROTEIN_STRUCTURAL_BIOLOGY_CONSORTIUM = "MEMBRANE_PROTEIN_STRUCTURAL_BIOLOGY_CONSORTIUM",
  MEMBRANE_PROTEIN_STRUCTURES_BY_SOLUTION_NMR = "MEMBRANE_PROTEIN_STRUCTURES_BY_SOLUTION_NMR",
  MIDWEST_CENTER_FOR_MACROMOLECULAR_RESEARCH = "MIDWEST_CENTER_FOR_MACROMOLECULAR_RESEARCH",
  MIDWEST_CENTER_FOR_STRUCTURAL_GENOMICS = "MIDWEST_CENTER_FOR_STRUCTURAL_GENOMICS",
  MITOCHONDRIAL_PROTEIN_PARTNERSHIP = "MITOCHONDRIAL_PROTEIN_PARTNERSHIP",
  MONTREAL_KINGSTON_BACTERIAL_STRUCTURAL_GENOMICS_INITIATIVE = "MONTREAL_KINGSTON_BACTERIAL_STRUCTURAL_GENOMICS_INITIATIVE",
  MYCOBACTERIUM_TUBERCULOSIS_STRUCTURAL_PROTEOMICS_PROJECT = "MYCOBACTERIUM_TUBERCULOSIS_STRUCTURAL_PROTEOMICS_PROJECT",
  NEW_YORK_CONSORTIUM_ON_MEMBRANE_PROTEIN_STRUCTURE = "NEW_YORK_CONSORTIUM_ON_MEMBRANE_PROTEIN_STRUCTURE",
  NEW_YORK_SGX_RESEARCH_CENTER_FOR_STRUCTURAL_GENOMICS = "NEW_YORK_SGX_RESEARCH_CENTER_FOR_STRUCTURAL_GENOMICS",
  NEW_YORK_STRUCTURAL_GENOMICS_RESEARCH_CONSORTIUM = "NEW_YORK_STRUCTURAL_GENOMICS_RESEARCH_CONSORTIUM",
  NEW_YORK_STRUCTURAL_GENOMI_X_RESEARCH_CONSORTIUM = "NEW_YORK_STRUCTURAL_GENOMI_X_RESEARCH_CONSORTIUM",
  NORTHEAST_STRUCTURAL_GENOMICS_CONSORTIUM = "NORTHEAST_STRUCTURAL_GENOMICS_CONSORTIUM",
  NUCLEOCYTOPLASMIC_TRANSPORT_A_TARGET_FOR_CELLULAR_CONTROL = "NUCLEOCYTOPLASMIC_TRANSPORT_A_TARGET_FOR_CELLULAR_CONTROL",
  ONTARIO_CENTRE_FOR_STRUCTURAL_PROTEOMICS = "ONTARIO_CENTRE_FOR_STRUCTURAL_PROTEOMICS",
  OXFORD_PROTEIN_PRODUCTION_FACILITY = "OXFORD_PROTEIN_PRODUCTION_FACILITY",
  PARIS_SUD_YEAST_STRUCTURAL_GENOMICS = "PARIS_SUD_YEAST_STRUCTURAL_GENOMICS",
  PARTNERSHIP_FOR_NUCLEAR_RECEPTOR_SIGNALING_CODE_BIOLOGY = "PARTNERSHIP_FOR_NUCLEAR_RECEPTOR_SIGNALING_CODE_BIOLOGY",
  PARTNERSHIP_FOR_STEM_CELL_BIOLOGY = "PARTNERSHIP_FOR_STEM_CELL_BIOLOGY",
  PARTNERSHIP_FOR_T_CELL_BIOLOGY = "PARTNERSHIP_FOR_T_CELL_BIOLOGY",
  PROGRAM_FOR_THE_CHARACTERIZATION_OF_SECRETED_EFFECTOR_PROTEINS = "PROGRAM_FOR_THE_CHARACTERIZATION_OF_SECRETED_EFFECTOR_PROTEINS",
  PROTEIN_STRUCTURE_FACTORY = "PROTEIN_STRUCTURE_FACTORY",
  RIKEN_STRUCTURAL_GENOMICS_PROTEOMICS_INITIATIVE = "RIKEN_STRUCTURAL_GENOMICS_PROTEOMICS_INITIATIVE",
  SCOTTISH_STRUCTURAL_PROTEOMICS_FACILITY = "SCOTTISH_STRUCTURAL_PROTEOMICS_FACILITY",
  SEATTLE_STRUCTURAL_GENOMICS_CENTER_FOR_INFECTIOUS_DISEASE = "SEATTLE_STRUCTURAL_GENOMICS_CENTER_FOR_INFECTIOUS_DISEASE",
  SOUTHEAST_COLLABORATORY_FOR_STRUCTURAL_GENOMICS = "SOUTHEAST_COLLABORATORY_FOR_STRUCTURAL_GENOMICS",
  SOUTH_AFRICA_STRUCTURAL_TARGETS_ANNOTATION_DATABASE = "SOUTH_AFRICA_STRUCTURAL_TARGETS_ANNOTATION_DATABASE",
  STRUCTURAL_GENOMICS_CONSORTIUM = "STRUCTURAL_GENOMICS_CONSORTIUM",
  STRUCTURAL_GENOMICS_CONSORTIUM_FOR_RESEARCH_ON_GENE_EXPRESSION = "STRUCTURAL_GENOMICS_CONSORTIUM_FOR_RESEARCH_ON_GENE_EXPRESSION",
  STRUCTURAL_GENOMICS_OF_PATHOGENIC_PROTOZOA_CONSORTIUM = "STRUCTURAL_GENOMICS_OF_PATHOGENIC_PROTOZOA_CONSORTIUM",
  STRUCTURAL_PROTEOMICS_IN_EUROPE = "STRUCTURAL_PROTEOMICS_IN_EUROPE",
  STRUCTURAL_PROTEOMICS_IN_EUROPE_2 = "STRUCTURAL_PROTEOMICS_IN_EUROPE_2",
  STRUCTURES_OF_MTB_PROTEINS_CONFERRING_SUSCEPTIBILITY_TO_KNOWN_MTB_INHIBITORS = "STRUCTURES_OF_MTB_PROTEINS_CONFERRING_SUSCEPTIBILITY_TO_KNOWN_MTB_INHIBITORS",
  STRUCTURE_2_FUNCTION_PROJECT = "STRUCTURE_2_FUNCTION_PROJECT",
  STRUCTURE_DYNAMICS_AND_ACTIVATION_MECHANISMS_OF_CHEMOKINE_RECEPTORS = "STRUCTURE_DYNAMICS_AND_ACTIVATION_MECHANISMS_OF_CHEMOKINE_RECEPTORS",
  STRUCTURE_FUNCTION_ANALYSIS_OF_POLYMORPHIC_CDI_TOXIN_IMMUNITY_PROTEIN_COMPLEXES = "STRUCTURE_FUNCTION_ANALYSIS_OF_POLYMORPHIC_CDI_TOXIN_IMMUNITY_PROTEIN_COMPLEXES",
  STRUCTURE_FUNCTION_STUDIES_OF_TIGHT_JUNCTION_MEMBRANE_PROTEINS = "STRUCTURE_FUNCTION_STUDIES_OF_TIGHT_JUNCTION_MEMBRANE_PROTEINS",
  TB_STRUCTURAL_GENOMICS_CONSORTIUM = "TB_STRUCTURAL_GENOMICS_CONSORTIUM",
  TRANSCONTINENTAL_EM_INITIATIVE_FOR_MEMBRANE_PROTEIN_STRUCTURE = "TRANSCONTINENTAL_EM_INITIATIVE_FOR_MEMBRANE_PROTEIN_STRUCTURE",
  TRANSMEMBRANE_PROTEIN_CENTER = "TRANSMEMBRANE_PROTEIN_CENTER"
}

export enum PdbxSgProjectId {
  _1 = "_1",
  _10 = "_10",
  _2 = "_2",
  _3 = "_3",
  _4 = "_4",
  _5 = "_5",
  _6 = "_6",
  _7 = "_7",
  _8 = "_8",
  _9 = "_9"
}

export enum PdbxSgProjectInitialOfCenter {
  ATCG_3_D = "ATCG_3_D",
  BIGS = "BIGS",
  BSGC = "BSGC",
  BSGI = "BSGI",
  CEBS = "CEBS",
  CELLMAT = "CELLMAT",
  CESG = "CESG",
  CHSAM = "CHSAM",
  CHTSB = "CHTSB",
  CSGID = "CSGID",
  CSMP = "CSMP",
  GPCR = "GPCR",
  IFN = "IFN",
  ISFI = "ISFI",
  ISPC = "ISPC",
  JCSG = "JCSG",
  MCMR = "MCMR",
  MCSG = "MCSG",
  MPID = "MPID",
  MPP = "MPP",
  MPSBC = "MPSBC",
  MP_SBY_NMR = "MP_SBY_NMR",
  MSGP = "MSGP",
  MSGPP = "MSGPP",
  MTBI = "MTBI",
  NAT_PRO = "NAT_PRO",
  NESG = "NESG",
  NH_RS = "NH_RS",
  NPC_XSTALS = "NPC_XSTALS",
  NYCOMPS = "NYCOMPS",
  NYSGRC = "NYSGRC",
  NYSGXRC = "NYSGXRC",
  OCSP = "OCSP",
  OPPF = "OPPF",
  PCSEP = "PCSEP",
  PSF = "PSF",
  RSGI = "RSGI",
  SASTAD = "SASTAD",
  SECSG = "SECSG",
  SGC = "SGC",
  SGCGES = "SGCGES",
  SGPP = "SGPP",
  SPINE = "SPINE",
  SPINE_2 = "SPINE_2",
  SSGCID = "SSGCID",
  SSPF = "SSPF",
  STEMCELL = "STEMCELL",
  S_2_F = "S_2_F",
  TBSGC = "TBSGC",
  TCELL = "TCELL",
  TEMIMPS = "TEMIMPS",
  TJMP = "TJMP",
  TMPC = "TMPC",
  TRANSPORT_PDB = "TRANSPORT_PDB",
  UC_4_CDI = "UC_4_CDI",
  XMTB = "XMTB",
  YSG = "YSG"
}

export enum PdbxSgProjectProjectName {
  ENZYME_FUNCTION_INITIATIVE = "ENZYME_FUNCTION_INITIATIVE",
  NIAID_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES = "NIAID_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES",
  NPPSFA_NATIONAL_PROJECT_ON_PROTEIN_STRUCTURAL_AND_FUNCTIONAL_ANALYSES = "NPPSFA_NATIONAL_PROJECT_ON_PROTEIN_STRUCTURAL_AND_FUNCTIONAL_ANALYSES",
  PSI_BIOLOGY = "PSI_BIOLOGY",
  PSI_PROTEIN_STRUCTURE_INITIATIVE = "PSI_PROTEIN_STRUCTURE_INITIATIVE"
}

export enum PdbxAuditRevisionDetailsDataContentType {
  NMR_RESTRAINTS = "NMR_RESTRAINTS",
  NMR_SHIFTS = "NMR_SHIFTS",
  STRUCTURE_FACTORS = "STRUCTURE_FACTORS",
  STRUCTURE_MODEL = "STRUCTURE_MODEL"
}

export enum PdbxAuditRevisionDetailsProvider {
  AUTHOR = "AUTHOR",
  REPOSITORY = "REPOSITORY"
}

export enum PdbxAuditRevisionDetailsType {
  COORDINATE_REPLACEMENT = "COORDINATE_REPLACEMENT",
  INITIAL_RELEASE = "INITIAL_RELEASE",
  OBSOLETE = "OBSOLETE"
}

export enum PdbxAuditRevisionHistoryDataContentType {
  NMR_RESTRAINTS = "NMR_RESTRAINTS",
  NMR_SHIFTS = "NMR_SHIFTS",
  STRUCTURE_FACTORS = "STRUCTURE_FACTORS",
  STRUCTURE_MODEL = "STRUCTURE_MODEL"
}

export enum PdbxDatabasePdbObsSprId {
  OBSLTE = "OBSLTE",
  SPRSDE = "SPRSDE"
}

export enum PdbxDatabaseStatusSgEntry {
  N = "N",
  Y = "Y"
}

export enum PdbxDatabaseStatusDepositSite {
  BMRB = "BMRB",
  BNL = "BNL",
  NDB = "NDB",
  PDBE = "PDBE",
  PDBJ = "PDBJ",
  RCSB = "RCSB"
}

export enum PdbxDatabaseStatusMethodsDevelopmentCategory {
  CAPRI = "CAPRI",
  CASD_NMR = "CASD_NMR",
  CASP = "CASP",
  D_3_R = "D_3_R",
  FOLD_IT = "FOLD_IT",
  GPCR_DOCK = "GPCR_DOCK",
  RNA_PUZZLES = "RNA_PUZZLES"
}

export enum PdbxDatabaseStatusPdbFormatCompatible {
  N = "N",
  Y = "Y"
}

export enum PdbxDatabaseStatusProcessSite {
  BNL = "BNL",
  NDB = "NDB",
  PDBE = "PDBE",
  PDBJ = "PDBJ",
  RCSB = "RCSB"
}

export enum PdbxDatabaseStatusStatusCode {
  AUCO = "AUCO",
  AUTH = "AUTH",
  BIB = "BIB",
  DEL = "DEL",
  HOLD = "HOLD",
  HPUB = "HPUB",
  OBS = "OBS",
  POLC = "POLC",
  PROC = "PROC",
  REFI = "REFI",
  REL = "REL",
  REPL = "REPL",
  REV = "REV",
  RMVD = "RMVD",
  TRSF = "TRSF",
  UPD = "UPD",
  WAIT = "WAIT",
  WDRN = "WDRN"
}

export enum PdbxDatabaseStatusStatusCodeCs {
  AUTH = "AUTH",
  HOLD = "HOLD",
  HPUB = "HPUB",
  OBS = "OBS",
  POLC = "POLC",
  PROC = "PROC",
  REL = "REL",
  REPL = "REPL",
  RMVD = "RMVD",
  WAIT = "WAIT",
  WDRN = "WDRN"
}

export enum PdbxDatabaseStatusStatusCodeMr {
  AUTH = "AUTH",
  HOLD = "HOLD",
  HPUB = "HPUB",
  OBS = "OBS",
  POLC = "POLC",
  PROC = "PROC",
  REL = "REL",
  REPL = "REPL",
  RMVD = "RMVD",
  WAIT = "WAIT",
  WDRN = "WDRN"
}

export enum PdbxDatabaseStatusStatusCodeSf {
  AUTH = "AUTH",
  HOLD = "HOLD",
  HPUB = "HPUB",
  OBS = "OBS",
  POLC = "POLC",
  PROC = "PROC",
  REL = "REL",
  REPL = "REPL",
  RMVD = "RMVD",
  WAIT = "WAIT",
  WDRN = "WDRN"
}

export enum PdbxDepositGroupGroupType {
  CHANGED_STATE = "CHANGED_STATE",
  GROUND_STATE = "GROUND_STATE",
  UNDEFINED = "UNDEFINED"
}

export enum PdbxMoleculeFeaturesClass {
  ANTAGONIST = "ANTAGONIST",
  ANTHELMINTIC = "ANTHELMINTIC",
  ANTIBIOTIC = "ANTIBIOTIC",
  ANTIBIOTIC_ANTHELMINTIC = "ANTIBIOTIC_ANTHELMINTIC",
  ANTIBIOTIC_ANTIMICROBIAL = "ANTIBIOTIC_ANTIMICROBIAL",
  ANTIBIOTIC_ANTINEOPLASTIC = "ANTIBIOTIC_ANTINEOPLASTIC",
  ANTICANCER = "ANTICANCER",
  ANTICOAGULANT = "ANTICOAGULANT",
  ANTICOAGULANT_ANTITHROMBOTIC = "ANTICOAGULANT_ANTITHROMBOTIC",
  ANTIFUNGAL = "ANTIFUNGAL",
  ANTIINFLAMMATORY = "ANTIINFLAMMATORY",
  ANTIMICROBIAL = "ANTIMICROBIAL",
  ANTIMICROBIAL_ANTIPARASITIC_ANTIBIOTIC = "ANTIMICROBIAL_ANTIPARASITIC_ANTIBIOTIC",
  ANTIMICROBIAL_ANTIRETROVIRAL = "ANTIMICROBIAL_ANTIRETROVIRAL",
  ANTIMICROBIAL_ANTITUMOR = "ANTIMICROBIAL_ANTITUMOR",
  ANTINEOPLASTIC = "ANTINEOPLASTIC",
  ANTIPARASITIC = "ANTIPARASITIC",
  ANTIRETROVIRAL = "ANTIRETROVIRAL",
  ANTITHROMBOTIC = "ANTITHROMBOTIC",
  ANTITUMOR = "ANTITUMOR",
  ANTIVIRAL = "ANTIVIRAL",
  CASPASE_INHIBITOR = "CASPASE_INHIBITOR",
  CHAPERONE_BINDING = "CHAPERONE_BINDING",
  ENZYME_INHIBITOR = "ENZYME_INHIBITOR",
  GROWTH_FACTOR = "GROWTH_FACTOR",
  IMMUNOSUPPRESSANT = "IMMUNOSUPPRESSANT",
  INHIBITOR = "INHIBITOR",
  LANTIBIOTIC = "LANTIBIOTIC",
  METABOLISM = "METABOLISM",
  METAL_TRANSPORT = "METAL_TRANSPORT",
  OXIDATION_REDUCTION = "OXIDATION_REDUCTION",
  RECEPTOR = "RECEPTOR",
  THROMBIN_INHIBITOR = "THROMBIN_INHIBITOR",
  THROMBIN_INHIBITOR_TRYPSIN_INHIBITOR = "THROMBIN_INHIBITOR_TRYPSIN_INHIBITOR",
  TOXIN = "TOXIN",
  TRANSPORT_ACTIVATOR = "TRANSPORT_ACTIVATOR",
  TRYPSIN_INHIBITOR = "TRYPSIN_INHIBITOR",
  UNKNOWN = "UNKNOWN"
}

export enum PdbxMoleculeFeaturesType {
  AMINOGLYCOSIDE = "AMINOGLYCOSIDE",
  AMINO_ACID = "AMINO_ACID",
  ANSAMYCIN = "ANSAMYCIN",
  ANTHRACYCLINE = "ANTHRACYCLINE",
  ANTHRAQUINONE = "ANTHRAQUINONE",
  CHALKOPHORE = "CHALKOPHORE",
  CHALKOPHORE_POLYPEPTIDE = "CHALKOPHORE_POLYPEPTIDE",
  CHROMOPHORE = "CHROMOPHORE",
  CYCLIC_DEPSIPEPTIDE = "CYCLIC_DEPSIPEPTIDE",
  CYCLIC_LIPOPEPTIDE = "CYCLIC_LIPOPEPTIDE",
  CYCLIC_PEPTIDE = "CYCLIC_PEPTIDE",
  GLYCOPEPTIDE = "GLYCOPEPTIDE",
  HETEROCYCLIC = "HETEROCYCLIC",
  IMINO_SUGAR = "IMINO_SUGAR",
  KETO_ACID = "KETO_ACID",
  LIPOGLYCOPEPTIDE = "LIPOGLYCOPEPTIDE",
  LIPOPEPTIDE = "LIPOPEPTIDE",
  MACROLIDE = "MACROLIDE",
  NON_POLYMER = "NON_POLYMER",
  NUCLEOSIDE = "NUCLEOSIDE",
  OLIGOPEPTIDE = "OLIGOPEPTIDE",
  OLIGOSACCHARIDE = "OLIGOSACCHARIDE",
  PEPTAIBOL = "PEPTAIBOL",
  PEPTIDE_LIKE = "PEPTIDE_LIKE",
  POLYCYCLIC = "POLYCYCLIC",
  POLYPEPTIDE = "POLYPEPTIDE",
  POLYSACCHARIDE = "POLYSACCHARIDE",
  QUINOLONE = "QUINOLONE",
  SIDEROPHORE = "SIDEROPHORE",
  THIOLACTONE = "THIOLACTONE",
  THIOPEPTIDE = "THIOPEPTIDE",
  UNKNOWN = "UNKNOWN"
}

export enum PdbxNmrExptlSampleState {
  ANISOTROPIC = "ANISOTROPIC",
  ISOTROPIC = "ISOTROPIC"
}

export enum PdbxNmrExptlSampleConditionsIonicStrengthUnits {
  M = "M",
  M_M = "M_M",
  NOT_DEFINED = "NOT_DEFINED"
}

export enum PdbxNmrExptlSampleConditionsPhUnits {
  NOT_DEFINED = "NOT_DEFINED",
  P_D = "P_D",
  P_H = "P_H",
  P_H_ = "P_H_"
}

export enum PdbxNmrExptlSampleConditionsTemperatureUnits {
  C = "C",
  K = "K",
  NOT_DEFINED = "NOT_DEFINED"
}

export enum PdbxNmrSampleDetailsType {
  BICELLE = "BICELLE",
  EMULSION = "EMULSION",
  FIBER = "FIBER",
  FIBROUS_PROTEIN = "FIBROUS_PROTEIN",
  FILAMENTOUS_VIRUS = "FILAMENTOUS_VIRUS",
  GEL_SOLID = "GEL_SOLID",
  GEL_SOLUTION = "GEL_SOLUTION",
  LIPOSOME = "LIPOSOME",
  LYOPHILIZED_POWDER = "LYOPHILIZED_POWDER",
  MEMBRANE = "MEMBRANE",
  MICELLE = "MICELLE",
  ORIENTED_MEMBRANE_FILM = "ORIENTED_MEMBRANE_FILM",
  POLYCRYSTALLINE_POWDER = "POLYCRYSTALLINE_POWDER",
  REVERSE_MICELLE = "REVERSE_MICELLE",
  SINGLE_CRYSTAL = "SINGLE_CRYSTAL",
  SOLID = "SOLID",
  SOLUTION = "SOLUTION"
}

export enum PdbxSerialCrystallographySampleDeliveryMethod {
  FIXED_TARGET = "FIXED_TARGET",
  INJECTION = "INJECTION"
}

export enum RcsbBindingSource {
  BINDINGDB = "BINDINGDB",
  BINDINGMOAD = "BINDINGMOAD",
  PDBBIND = "PDBBIND"
}

export enum RefineLsMatrixType {
  ATOMBLOCK = "ATOMBLOCK",
  DIAGONAL = "DIAGONAL",
  FULL = "FULL",
  FULLCYCLE = "FULLCYCLE",
  SPARSE = "SPARSE",
  USERBLOCK = "USERBLOCK"
}

export enum RefinePdbxTlsResidualAdpFlag {
  LIKELY_RESIDUAL = "LIKELY_RESIDUAL",
  UNVERIFIED = "UNVERIFIED"
}

export enum SoftwareLanguage {
  ADA = "ADA",
  ASSEMBLER = "ASSEMBLER",
  AWK = "AWK",
  BASIC = "BASIC",
  C = "C",
  CSH = "CSH",
  C_ = "C_",
  C_C = "C_C",
  FORTRAN = "FORTRAN",
  FORTRAN_77 = "FORTRAN_77",
  FORTRAN_77_ = "FORTRAN_77_",
  FORTRAN_90 = "FORTRAN_90",
  JAVA = "JAVA",
  JAVA_FORTRAN = "JAVA_FORTRAN",
  KSH = "KSH",
  OTHER = "OTHER",
  PASCAL = "PASCAL",
  PERL = "PERL",
  PYTHON = "PYTHON",
  PYTHON_C = "PYTHON_C",
  SH = "SH",
  TCL = "TCL"
}

export enum SoftwareType {
  FILTER = "FILTER",
  JIFFY = "JIFFY",
  LIBRARY = "LIBRARY",
  OTHER = "OTHER",
  PACKAGE = "PACKAGE",
  PROGRAM = "PROGRAM"
}

export enum StructPdbxCaspFlag {
  N = "N",
  Y = "Y"
}

export enum SymmetryCellSetting {
  CUBIC = "CUBIC",
  HEXAGONAL = "HEXAGONAL",
  MONOCLINIC = "MONOCLINIC",
  ORTHORHOMBIC = "ORTHORHOMBIC",
  RHOMBOHEDRAL = "RHOMBOHEDRAL",
  TETRAGONAL = "TETRAGONAL",
  TRICLINIC = "TRICLINIC",
  TRIGONAL = "TRIGONAL"
}

// ====================================================
// END: Typescript template
// ====================================================

// ====================================================
// Documents
// ====================================================

export namespace AssemblySymmetry {
  export type Variables = {
    readonly pdbId: string;
  };

  export type Query = {
    readonly __typename?: "Query";

    readonly assemblies?: ReadonlyArray<Assemblies | null> | null;
  };

  export type Assemblies = {
    readonly __typename?: "CoreAssembly";

    readonly pdbx_struct_assembly?: PdbxStructAssembly | null;

    readonly rcsb_struct_symmetry?: ReadonlyArray<RcsbStructSymmetry | null> | null;

    readonly rcsb_struct_symmetry_provenance?: string | null;
  };

  export type PdbxStructAssembly = {
    readonly __typename?: "PdbxStructAssembly";

    readonly id: string;
  };

  export type RcsbStructSymmetry = {
    readonly __typename?: "RcsbStructSymmetry";

    readonly clusters: ReadonlyArray<Clusters | null>;

    readonly kind: RcsbStructSymmetryKind;

    readonly oligomeric_state: string;

    readonly rotation_axes?: ReadonlyArray<RotationAxes | null> | null;

    readonly stoichiometry: ReadonlyArray<string | null>;

    readonly symbol: string;

    readonly type: RcsbStructSymmetryType;
  };

  export type Clusters = {
    readonly __typename?: "RcsbStructSymmetryClusters";

    readonly avg_rmsd?: number | null;

    readonly members: ReadonlyArray<Members | null>;
  };

  export type Members = {
    readonly __typename?: "ClustersMembers";

    readonly asym_id: string;

    readonly pdbx_struct_oper_list_ids?: ReadonlyArray<string | null> | null;
  };

  export type RotationAxes = {
    readonly __typename?: "RcsbStructSymmetryRotationAxes";

    readonly start: ReadonlyArray<number | null>;

    readonly end: ReadonlyArray<number | null>;

    readonly order?: number | null;
  };
}
