import { Color } from '@molstar/core/util/color';
import { Task } from '@molstar/core/task';
import { CIF } from '@molstar/io/reader/cif';
import { PluginContext } from '@molstar/plugin/context';
import { DefaultPluginSpec } from '@molstar/plugin/default-spec';
import { createPluginUI } from '@molstar/plugin-ui';
import { renderReact18 } from '@molstar/plugin-ui/react18';
import { DefaultPluginUISpec } from '@molstar/plugin-ui/default-spec';
import type { PluginUISpec } from '@molstar/plugin-ui/spec';
import { HeadlessPluginContext } from '@molstar/plugin-headless/context';
import type { ExternalModules } from '@molstar/plugin-headless/screenshot';
import { MVSData } from '@molstar/mvs-builder/mvs-data';
import { MolScriptBuilder as B, compileScript } from '@molstar/mvs-builder/molql';
import type { Expression } from '@molstar/query-language/language/expression';
import { SymbolMap } from '@molstar/query-language/language/symbol-table';

const color: number = Color(0xff0000);
const task: Task<number> = Task.create('types smoke', async () => 1);
const parse = CIF.parse('data_smoke\n');
const plugin = new PluginContext(DefaultPluginSpec());
const uiSpec: PluginUISpec = DefaultPluginUISpec();
const headless = (external: ExternalModules) => new HeadlessPluginContext(external, DefaultPluginSpec());
const ui = (target: HTMLElement) => createPluginUI({ target, render: renderReact18, spec: uiSpec });
const mvs = MVSData.createBuilder().getState();
const molql: Expression = B.core.logic.and([compileScript('pymol', 'all'), compileScript('jmol', 'all')]);
const element = <div data-smoke="types">consumer JSX</div>;
void color;
void task;
void parse;
void plugin;
void headless;
void ui;
void MVSData.validationIssues(mvs);
void MVSData.validationIssues(mvs, { getMolQLSymbol: (name) => SymbolMap[name] });
void molql;
void element;
