/**
 * Copyright (c) 2026 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author Alexander Rose <alexander.rose@weirdbyte.de>
 */

import { SyminfoEntry, stripSettingQualifier } from './parse';
import { CuratedBySpacegroupNumber } from './curated';

function quote(s: string): string {
    return `'${s.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')}'`;
}

function quoteArray(items: readonly string[]): string {
    return `[${items.map(quote).join(', ')}]`;
}

const FileHeader = (extra: string) => `/**
 * Copyright (c) 2026 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * Code-generated by \`src/cli/syminfo\` from \`data/sym/syminfo.lib\` - do not
 * edit manually. Regenerate with \`npm run gen-syminfo\`.
 */

${extra}`;

export interface RawEntry {
    readonly itaNumber: number;
    readonly ccp4Number: number;
    readonly names: readonly string[];
    readonly hall: string;
    readonly basisop: string;
}

/**
 * Merges parsed `syminfo.lib` entries with the independently-crafted
 * (comma-free) Hall symbols/names for the 268 CCP4-numbered settings (see
 * `./curated`), so `operatorsFromHall` keeps producing byte-identical
 * results for those. `names`/`hall` for the rest come straight from
 * `syminfo.lib` (`symbol old`/`xHM`/`Hall`).
 */
export function buildRawEntries(entries: readonly SyminfoEntry[]): RawEntry[] {
    return entries.map(entry => {
        const ccp4Number = entry.ccp4;
        const curated = ccp4Number !== 0 ? CuratedBySpacegroupNumber[ccp4Number] : undefined;
        const names = curated?.[0] ?? (entry.old.length > 0 ? entry.old : (entry.xHM ? [stripSettingQualifier(entry.xHM)] : []));
        const hall = curated?.[1] ?? entry.hall;
        return { itaNumber: entry.number, ccp4Number, names, hall, basisop: entry.basisop };
    });
}

/** Generates `src/mol-math/geometry/spacegroup/syminfo.ts` (`RawSpacegroupData`). */
export function generateSpacegroupSyminfoTs(entries: readonly SyminfoEntry[]): string {
    const rawEntries = buildRawEntries(entries);
    const lines = rawEntries.map(e => {
        return `    [${e.itaNumber}, ${e.ccp4Number}, ${quoteArray(e.names)}, ${quote(e.hall)}, ${quote(e.basisop)}],`;
    });
    return FileHeader(`/**
 * \`[itaNumber, ccp4Number, names, hall, basisop]\` tuples for every
 * \`syminfo.lib\` setting (${rawEntries.length} total - all CCP4-numbered
 * settings AND non-numbered axis/cell/origin alternatives). See
 * \`../../../cli/syminfo\` for how this is generated, and \`./tables\`'s
 * \`SpacegroupEntry\`/\`SpacegroupData\` for the friendlier object-shaped
 * form consumed by the rest of the codebase.
 */
export type RawSpacegroupEntry = readonly [itaNumber: number, ccp4Number: number, names: readonly string[], hall: string, basisop: string];

export const RawSpacegroupData: ReadonlyArray<RawSpacegroupEntry> = [
${lines.join('\n')}
];
`);
}

/**
 * Generates `src/mol-math/geometry/spacegroup/_spec/syminfo.lib.ts`.
 */
export function generateSyminfoLibSpecTs(entries: readonly SyminfoEntry[]): string {
    const lines = entries.map(e => {
        return `    { number: ${e.number}, ccp4: ${e.ccp4}, hall: ${quote(e.hall)}, xHM: ${quote(e.xHM)}, basisop: ${quote(e.basisop)}, old: ${quoteArray(e.old)}, symops: ${quoteArray(e.symops)}, cenops: ${quoteArray(e.cenops)} },`;
    });
    return FileHeader(`/**
 * A single \`begin_spacegroup...end_spacegroup\` block from CCP4
 * \`data/sym/syminfo.lib\`, reduced to the fields needed to independently
 * reconstruct its full operator set and its accepted alias names. Test-only:
 * \`../syminfo.ts\`'s production \`RawSpacegroupData\` (also code-generated,
 * see \`src/cli/syminfo\`, and mapped into the friendlier object-shaped
 * \`SpacegroupEntry\`/\`SpacegroupData\` by \`../tables.ts\`) - this file
 * exists purely as an independent regression oracle for
 * \`_spec/notation.spec.ts\` and \`_spec/tables.spec.ts\`.
 */
export interface SyminfoEntry {
    /** International Tables (ITA) spacegroup number. */
    readonly number: number;
    /** CCP4-style spacegroup number (\`0\` if this setting has none). */
    readonly ccp4: number;
    /** Raw \`symbol Hall\` value (quotes/leading space stripped, any \`(...)\` suffix kept as-is). */
    readonly hall: string;
    /** Raw \`symbol xHM\` value (quotes stripped, may carry a \` :H\`/\`:R\`/\`:1\`/\`:2\` setting-qualifier suffix). */
    readonly xHM: string;
    /** Raw \`basisop\` change-of-basis coordinate-triplet expression, e.g. \`'z,x,y'\`. */
    readonly basisop: string;
    /** Non-empty \`symbol old\` alias name tokens (there may be zero, one, or several). */
    readonly old: readonly string[];
    /** \`symop\` coordinate-triplet expressions (point-group coset representatives). */
    readonly symops: readonly string[];
    /** \`cenop\` coordinate-triplet expressions (lattice-centering translations). */
    readonly cenops: readonly string[];
}

export const syminfoEntries: readonly SyminfoEntry[] = [
${lines.join('\n')}
];
`);
}
